#!/bin/bash

###GNU + ESSL + CUDA + TALSH:

PATH_TO_TALSH="~/TAL_SH"
PATH_TO_CUDA="/sw/summit/cuda/9.2.148"
PATH_TO_ESSL="/sw/summit/essl/6.1.0-2/essl/6.1"
PATH_TO_XLF="/sw/summit/xl/16.1.1-1/xlf/16.1.1"

LINK_TO_TALSH="-L${PATH_TO_TALSH} -ltalsh"
LINK_TO_CUDA="-L${PATH_TO_CUDA}/lib64 -lcublas -lcudart -lnvToolsExt"
LINK_TO_ESSL="-L${PATH_TO_ESSL}/lib64 -L${PATH_TO_XLF}/lib -lessl -lxlf90_r -lxlfmath"


#### CUDA
echo "g++  -c main.cpp"
g++ -c main.cpp -DBLAS_ESSL -I ~/TAL_SH -I${PATH_TO_CUDA}/include -I${PATH_TO_ESSL}/include -O3 -fopenmp -std=c++14 -fPIC  -fpermissive
echo "g++  main.o main.cpp"
g++  main.o ~/TAL_SH/libtalsh.a ${LINK_TO_ESSL}  ${LINK_TO_CUDA} -fopenmp -lgfortran -fPIC -o main  -fpermissive


#### NOCUDA
#echo "g++  -c main.cpp"
#g++ -c main.cpp -DBLAS_ESSL -I ~/TAL_SH -I${PATH_TO_CUDA}/include -I${PATH_TO_ESSL}/include -O3 -fopenmp -std=c++14 -fPIC  -fpermissive
#echo "g++  main.o main.cpp"
#g++  main.o ~/TAL_SH/libtalsh.a ${LINK_TO_ESSL} -fopenmp -lgfortran -fPIC -o main  -fpermissive
